from dotenv import load_dotenv
import os

load_dotenv()

class ENV_Config():
    FE_BASE_URL=os.getenv("FE_BASE_URL")
    MONGODB_URI = os.getenv("MONGODB_URI")
    MONGO_DB = os.getenv("MONGO_DB")
    
    EMAIL_HOST=os.getenv("EMAIL_HOST")
    EMAIL_PORT=os.getenv("EMAIL_PORT")
    EMAIL_USER=os.getenv("EMAIL_USER")
    EMAIL_PASS=os.getenv("EMAIL_PASS")
    
    JWT_SECRET_KEY=os.getenv("SECRET_KEY")
    JWT_ALGORITHM=os.getenv("ALGORITHM")
    JWT_ACCESS_TOKEN_EXPIRE_MINUTES=os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES")
    
    CLOUDINARY_CLOUD_NAME=os.getenv("CLOUDINARY_CLOUD_NAME")
    CLOUDINARY_API_KEY=os.getenv("CLOUDINARY_API_KEY")
    CLOUDINARY_API_SECRET=os.getenv("CLOUDINARY_API_SECRET")
    
    STRIPE_PUBLISHABLE_KEY=os.getenv("STRIPE_PUBLISHABLE_KEY")
    STRIPE_SECRET_KEY=os.getenv("STRIPE_SECRET_KEY")
    STRIPE_WEBHOOK_SECRET=os.getenv("STRIPE_WEBHOOK_SECRET")
    STRIPE_PAYMENT_SUCCESS_URL=os.getenv("STRIPE_PAYMENT_SUCCESS_URL")
    STRIPE_PAYMENT_FAILED_URL=os.getenv("STRIPE_PAYMENT_FAILED_URL")